In [1]:
#import 丟這裡
#no moudle 請 pip install moudle 或是 python -m pip install moudle
import numpy as np 
from scipy.spatial import distance as dist
import cv2 
from imutils import contours
from imutils import perspective
import imutils
import cv2
import utils

由基準物判別物件大小(10元硬幣?)
---
2D

輪廓展示圖
----


In [8]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img_original=cv2.imread('coin_2.jpg')
img_original = imutils.resize(img_original,height = 500)
img_gray=cv2.cvtColor(img_original,cv2.COLOR_BGR2GRAY)
img_gray = cv2.GaussianBlur(img_gray,(5,5),0)
img_edged = cv2.Canny(img_gray,70,200)
img_edged = cv2.dilate(img_edged,None,iterations = 1)
img_edged = cv2.erode(img_edged,None,iterations = 1)

retv,thresh=cv2.threshold(img_gray,125,255,1)

contours,hierarchy=cv2.findContours(thresh,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)

cv2.drawContours(img_original,contours,-1,(0,0,255),3,lineType=cv2.LINE_AA)

cv2.imshow('Contours',img_original)
cv2.waitKey()
cv2.destroyAllWindows()

In [14]:
def show(name,img):
    cv2.imshow(name,img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
def midpoint(ptA,ptB):
    return ((ptA[0] + ptB[0]) * 0.5 , (ptA[1] + ptB[1]) * 0.5)
###圖像處理###
img = cv2.imread('coin_2.jpg')
width = 25
img = imutils.resize(img,height = 500)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)#灰度
gray = cv2.GaussianBlur(gray,(5,5),0)
edged = cv2.Canny(gray,70,200)
edged = cv2.dilate(edged,None,iterations = 1)
edged = cv2.erode(edged,None,iterations = 1)
#############
cnts,_ = cv2.findContours(edged,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)#尋找輪廓
(cnts,_) = contours.sort_contours(cnts)#左到右排
pixelPerMetricX = 0
pixelPerMetricY = 0
order = 1
for c in cnts:
    if cv2.contourArea(c) < 100:
        #除躁點
        continue 
    orig = img.copy()
    box = cv2.minAreaRect(c)#生成最小外接矩形
    print(box)
    box = cv2.boxPoints(box)#頂點座標
    print(box)
    box = box.astype('int')
    print(box)
    box = perspective.order_points(box)
    print(box)
    cv2.drawContours(orig,[box.astype(int)],0,(0,255,0),2)
    for x,y in box:
        cv2.circle(orig,(int(x),int(y)),5,(0,0,255),3)
    (tl,tr,br,bl) = box 
    (tltrX,tltrY) = midpoint(tl,tr)
    (tlblX,tlblY) = midpoint(tl,bl)
    (blbrX,blbrY) = midpoint(bl,br)
    (trbrX,trbrY) = midpoint(tr,br)
    cv2.circle(orig,(int(tltrX),int(tltrY)),5,(183,197,57),-1)
    cv2.circle(orig,(int(tlblX),int(tlblY)),5,(183,197,57),-1)
    cv2.circle(orig,(int(blbrX),int(blbrY)),5,(183,197,57),-1)
    cv2.circle(orig,(int(trbrX),int(trbrY)),5,(183,197,57),-1)
    cv2.line(orig,(int(tltrX),int(tltrY)),(int(blbrX),int(blbrY)),(255,0,0),2)
    cv2.line(orig,(int(tlblX),int(tlblY)),(int(trbrX),int(trbrY)),(255,0,0),2)
  
    dA = dist.euclidean((tltrX,tltrY),(blbrX,blbrY))
   
    dB = dist.euclidean((tlblX,tlblY),(trbrX,trbrY))
    if pixelPerMetricX == 0 or pixelPerMetricY == 0:
        pixelPerMetricX = dB / width
        pixelPerMetricY = dA / width
    dimA = dA / pixelPerMetricY
    dimB = dB / pixelPerMetricX
    cv2.putText(orig,"{:.1f}mm".format(dimB),(int(tltrX)-10,int(tltrY)),cv2.FONT_HERSHEY_COMPLEX,0.6,(255,255,255),1)
    cv2.putText(orig,"{:.1f}mm".format(dimA),(int(trbrX)-10,int(trbrY)),cv2.FONT_HERSHEY_COMPLEX,0.6,(255,255,255),1)
    cv2.imwrite('{}.jpg'.format(order),orig)
    order += 1
show("1",orig)
#圖會存資料夾內

((211.25836181640625, 143.31411743164062), (102.73626708984375, 90.42010498046875), 37.5685920715332)
[[142.97769 147.82898]
 [198.10782  76.15984]
 [279.53903 138.79926]
 [224.4089  210.46838]]
[[142 147]
 [198  76]
 [279 138]
 [224 210]]
[[198.  76.]
 [279. 138.]
 [224. 210.]
 [142. 147.]]
((411.5, 313.5), (243.0, 67.0), 90.0)
[[378. 192.]
 [445. 192.]
 [445. 435.]
 [378. 435.]]
[[378 192]
 [445 192]
 [445 435]
 [378 435]]
[[378. 192.]
 [445. 192.]
 [445. 435.]
 [378. 435.]]
((683.0164794921875, 217.5321044921875), (260.7268981933594, 163.5819549560547), 89.3839340209961)
[[599.82855  88.05562]
 [763.40106  86.29677]
 [766.2044  347.0086 ]
 [602.6319  348.76746]]
[[599  88]
 [763  86]
 [766 347]
 [602 348]]
[[599.  88.]
 [763.  86.]
 [766. 347.]
 [602. 348.]]


下面兩塊是其他作法
===


In [ ]:

  
###################################
webcam = False
path = 'test_3.png'
cap = cv2.VideoCapture(1)
cap.set(10, 160)
cap.set(3, 1920)
cap.set(4, 1080)
scale = 3
wP = 210 * scale
hP = 297 * scale
###################################
  
while True:
    if webcam:
        success, img = cap.read()
    else:
        img = cv2.imread(path)
  
    imgContours, conts = getContours(img, minArea=50000, filter=4)
    if len(conts) != 0:
        biggest = conts[0][2]
        # print(biggest)
        imgWarp = warpImg(img, biggest, wP, hP)
        imgContours2, conts2 = getContours(imgWarp,
                                                 minArea=2000, filter=4,
                                                 cThr=[50, 50], draw=False)
        if len(conts) != 0:
            for obj in conts2:
                cv2.polylines(imgContours2, [obj[2]], True, (0, 255, 0), 2)
                nPoints = reorder(obj[2])
                nW = round((findDis(nPoints[0][0] // scale, nPoints[1][0] // scale) / 10), 1)
                nH = round((findDis(nPoints[0][0] // scale, nPoints[2][0] // scale) / 10), 1)
                cv2.arrowedLine(imgContours2, (nPoints[0][0][0], nPoints[0][0][1]),
                                (nPoints[1][0][0], nPoints[1][0][1]),
                                (255, 0, 255), 3, 8, 0, 0.05)
                cv2.arrowedLine(imgContours2, (nPoints[0][0][0], nPoints[0][0][1]),
                                (nPoints[2][0][0], nPoints[2][0][1]),
                                (255, 0, 255), 3, 8, 0, 0.05)
                x, y, w, h = obj[3]
                cv2.putText(imgContours2, '{}cm'.format(nW), (x + 30, y - 10), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1.5,
                            (255, 0, 255), 2)
                cv2.putText(imgContours2, '{}cm'.format(nH), (x - 70, y + h // 2), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1.5,
                            (255, 0, 255), 2)
        cv2.imshow('A4', imgContours2)
  
    img = cv2.resize(img, (0, 0), None, 0.5, 0.5)
    cv2.imshow('Original', img)
    if cv2.waitKey(1) & 0xFF ==27:
        break

以上為圖片部分的辨識
</br>////////////////////////////////////////////////////////

機器學習 框框+辨識硬幣

In [9]:
import cv2
import numpy as np
import pickle
import matplotlib.pyplot as plt

cap = cv2.VideoCapture(0) #抓拍视频，0为id号

while True:
    ret,frame = cap.read() #ret是返回下一帧，frame是读取该文件的内容
    # Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # Display the resulting frame
    cv2.imshow('frame',gray)
    #等待1秒按下q键退出
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

In [10]:
import cv2
import numpy as np
import pickle
import matplotlib.pyplot as plt

cap = cv2.VideoCapture(0)
index = 0
while True:
    ret,frame = cap.read()
    # Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # Display the resulting frame
    cv2.imshow('frame',gray)
    #等待1秒，按下则将图片写入kk.jpg,且index文件数+1；按下q则退出
    if cv2.waitKey(1) & 0xFF == ord('p'):
        cv2.imwrite("kk.jpg",frame)
        index = index + 1
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()